from dotenv import load_dotenv
import os

load_dotenv()

POSTGRES_DB_CONNECTION=os.getenv("POSTGRES_DB_CONNECTION")
SECRET_KEY=os.getenv("SECRET_KEY")
ALGORITHM=os.getenv("ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES=os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES")
REFRESH_TOKEN_EXPIRE_MINUTES=os.getenv("REFRESH_TOKEN_EXPIRE_MINUTES")